# This is a basic workflow to help you get started with Actions

name: Daily Build

# Controls when the workflow will run
on:
  schedule:
    - cron: 0 3 * * *
  workflow_dispatch:

jobs:
  trigger_docker:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger build
        run: curl -X POST ${{ secrets.DOCKERHUB_TRIGGER }}
